apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: donprecious/reverseproxy:v3
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "20Mi"
            cpu: "10m"
          limits:
            memory: "50Mi"
            cpu: "20m"  
        ports:
        -  containerPort: 8080
        envFrom:
        - configMapRef:
           name: example-configmap 
        - secretRef:
            name: env-secret-credentials