apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-user
  labels:
    app: udagram-api-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-user
  template:
    metadata:
      labels:
        app: udagram-api-user
    spec:
      containers:
      - name: udagram-api-user
        image: donprecious/udagram-api-user:v1
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
           name: example-configmap 
        - secretRef:
            name: env-secret-credentials
        resources:
          requests:
            memory: "1000Mi"
            cpu: "250m"
          limits:
            memory: "2000Mi"
            cpu: "500m"  