apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  labels:
    run: reverseproxy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: reverse-port
  selector:
    run: reverseproxy