apiVersion: v1
kind: Service
metadata:
  name: udagram-api-feed
  labels:
    run: udagram-api-feed
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: feed-port
  type: ClusterIP
  selector:
    run: udagram-api-feed