language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  # - docker build -t udagram-api-feed .
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-user donprecious/udagram-api-user:v2
  - docker tag udagram-api-feed donprecious/udagram-api-feed:v2
  - docker tag udagram-frontend donprecious/udagram-frontend:v3
  - docker tag reverseproxy donprecious/reverseproxy:v3
# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push donprecious/udagram-api-user:v2
  - docker push donprecious/udagram-api-feed:v2
  - docker push donprecious/udagram-frontend:v3
  - docker push donprecious/reverseproxy:v3